spring:
  ai:
    vectorstore:
      mongodb:
        initialize-schema: false
        index-name: vector_index
        collection-name: commercial-activities
        path-name: embeddings
        metadata-fields-to-filter:
          - town
    ollama:
      base-url: change-it
      embedding:
        enabled: true
        model: bge-m3
      chat:
        enabled: true
        options:
          model: llava:7b
          temperature: 0f
  data:
    mongodb:
      uri: change-it
      database: vector-search
