springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    
logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG

spring:
  application.name: commercial-activities
  ai:
    ollama:
      base-url: change-it
      embedding:
        enabled: true
        model: bge-m3:567m
      chat:
        multimodal:
          # gemma3:4b/27b
          model: gemma3:4b
          temperature: 0f
        rag:
          # gemma3:1b/4b/12b/27b, deepseek-r1:7b/14b/32b, qwq:32b
          model: gemma3:12b

  data:
    mongodb:
      uri: change-it
      database: change-it

