spring:
  ai:
    vectorstore:
      mongodb:
        initialize-schema: true
        index-name: vector_index
        collection-name: commercial-activities
        path-name: embedding
        num-dimensions: 1024
        fields-to-filter:
          - town
          - categories
    ollama:
      base-url: change-it
      embedding:
        enabled: true
        model: mxbai-embed-large
      chat:
        enabled: true
        options:
          model: llava:7b
          temperature: 0f
  data:
    mongodb:
      uri: change-it
      database: vector-search
